import json
import string

def loadSplitFiles(fname):
	''' Yield all the files in a directory generated by the unix 'split' command,
	starting with a given prefix'''

	abet = string.ascii_lowercase
	for a in abet:
		for b in abet:
			try:
				with open(fname+a+b, 'r') as f:
					yield f
				print fname+a+b
			except:
				return

def loadJsonLines(f):
	''' Iterate over all documents in a json-lines file '''
	for l in f.readlines():
 		data = json.loads(l)
 		yield data

def loadSplitJsonLines(fname):
	 for f in loadSplitFiles(fname):
	 	for l in loadJsonLines(f):
	 		yield l
